version: "2"

services:
  airflow-webserver:
    image: eeacms/airflow:0.0.1
    volumes:
      - crawler-config-volume:/custom_config
    user: "50000:50000"
    depends_on:
      - redis
      - postgres
    environment:
      AIRFLOW_VAR_INDEXED_WEBSITES: '[]'
      SENTRY_DSN: ''

      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__CORE__PARALLELISM: 128
      AIRFLOW__CORE__DAG_CONCURRENCY: 64
    command: webserver
    ports:
      - "8100:8080"

    restart: always

  airflow-scheduler:
    image: eeacms/airflow:0.0.1
    volumes:
      - crawler-config-volume:/custom_config
    user: "50000:50000"
    depends_on:
      - redis
      - postgres
    environment:
      AIRFLOW_VAR_INDEXED_WEBSITES: '[]'
      SENTRY_DSN: ''

      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__CORE__PARALLELISM: 128
      AIRFLOW__CORE__DAG_CONCURRENCY: 64
    command: scheduler
    restart: always

  airflow-worker:
    image: eeacms/airflow:0.0.1
    volumes:
      - crawler-config-volume:/custom_config
    user: "50000:50000"
    depends_on:
      - redis
      - postgres
    environment:
      AIRFLOW_VAR_INDEXED_WEBSITES: '[]'
      SENTRY_DSN: ''

      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__CORE__PARALLELISM: 128
      AIRFLOW__CORE__DAG_CONCURRENCY: 64
    command: celery worker
    restart: always

  airflow-init:
    image: eeacms/airflow:0.0.1
    volumes:
      - crawler-config-volume:/custom_config
    user: "50000:50000"
    depends_on:
      - redis
      - postgres
    command: version
    environment:
      AIRFLOW_VAR_INDEXED_WEBSITES: '[]'
      SENTRY_DSN: ''

      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__CORE__PARALLELISM: 128
      AIRFLOW__CORE__DAG_CONCURRENCY: 64
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow

  flower:
    image: eeacms/airflow:0.0.1
    volumes:
      - crawler-config-volume:/custom_config
    user: "50000:50000"
    depends_on:
      - redis
      - postgres
    environment:
      AIRFLOW_VAR_INDEXED_WEBSITES: '[]'
      SENTRY_DSN: ''

      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__CORE__PARALLELISM: 128
      AIRFLOW__CORE__DAG_CONCURRENCY: 64
    command: celery flower
    ports:
      - "5555:5555"

    restart: always

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    restart: always

  rabbitmq:
    image: eeacms/rabbitmq:3.7.15-1
    environment:
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
      TZ: Europe/Copenhagen
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  logstash:
    image: eeacms/logstash
    volumes:
      - crawler-config-volume:/custom_config

  eea-crawler-config:
    image: eeacms/eea-crawler:0.0.1
    environment:
      github_repo: https://github.com/eea/eea-crawler
      DEV_ENV: "false"
      TZ: Europe/Copenhagen
    volumes:
      - crawler-config-volume:/custom_config

  elastic:
    image: eeacms/elastic:7
    ports:
      - 9200:9200
    depends_on:
      - elastic-sysctl

    environment:
      - "cluster.name=elastic7"
      - "node.name=elastics7_standalone"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "name=elastic7"
      - "elastic_password=qwerty"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4073741824
    mem_swappiness: 0
    cap_add:
      - IPC_LOCK

    volumes_from:
      - elastic-storage-volume

  elastic-sysctl:
    network_mode: none
    image: rawmind/alpine-sysctl:0.1
    privileged: true
    environment:
      - "SYSCTL_KEY=vm.max_map_count"
      - "SYSCTL_VALUE=262144"

  elastic-storage-volume:
    network_mode: none
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      - SERVICE_UID=1000
      - SERVICE_GID=1000
      - SERVICE_VOLUME=/usr/share/elasticsearch/data
    volumes:
      - elastic-storage-volume:/usr/share/elasticsearch/data


volumes:
  postgres-db-volume:
  rabbitmq-volume:
  crawler-config-volume:
    driver: local
  elastic-storage-volume:
    driver: local
